Тестируем класс `MyClass`.

Обратите внимание, что вызов метода `setUp` идёт до вызова каждого тестового метода, аналогично `tearDown` после каждого теста. 
Очень часто используют `setUp` чтобы задать данные для тестов, `tearDown` чтобы их очистить.

Проверку вызова ошибок можно произвести 2-умя способами:
* self.assertRaises(<Вызываемый класс ошибки>, <функция которую применяют на данные>, <данные>)
* с помощью менеджера контекста `with`. 
  ```python 
    with self.assertRaises(<Вызываемый класс ошибки>): 
        <действие в котором произойдёт ошибка>
  ```
